# -*- coding: utf-8 -*-

################################################################################
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1083, 718)
        # MainWindow.setStyleSheet(u"background-color:  #ffffff")
        # self.centralwidget = QWidget(MainWindow)
        # self.centralwidget.setObjectName(u"centralwidget")
        # self.centralwidget.setMinimumSize(QSize(1000, 500))
        # self.verticalLayout = QVBoxLayout(self.centralwidget)
        # self.verticalLayout.setSpacing(0)
        # self.verticalLayout.setObjectName(u"verticalLayout")
        # self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        # self.Content_Area = QFrame(self.centralwidget)
        # self.Content_Area.setObjectName(u"Content_Area")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Content_Area.sizePolicy().hasHeightForWidth())
        self.Content_Area.setSizePolicy(sizePolicy)
        self.Content_Area.setStyleSheet(u"background-color: rgb(102, 100, 101);\n"
"")
        self.Content_Area.setFrameShape(QFrame.NoFrame)
        self.Content_Area.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.Content_Area)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.Content_Area)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet(u"background-color: white\n"
";")
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.menu_button_holder = QFrame(self.frame_3)
        self.menu_button_holder.setObjectName(u"menu_button_holder")
        self.menu_button_holder.setMinimumSize(QSize(120, 120))
        self.menu_button_holder.setMaximumSize(QSize(120, 1232333))
        self.informations_page_btn = QPushButton(self.menu_button_holder)
        self.informations_page_btn.setObjectName(u"informations_page_btn")
        self.informations_page_btn.setGeometry(QRect(-15, 80, 161, 34))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.informations_page_btn.sizePolicy().hasHeightForWidth())
        self.informations_page_btn.setSizePolicy(sizePolicy1)
        self.informations_page_btn.setAutoFillBackground(False)
        self.informations_page_btn.setStyleSheet(u" \n"
"color: rgb(0, 0, 0);")
        self.rpc_page_btn = QPushButton(self.menu_button_holder)
        self.rpc_page_btn.setObjectName(u"rpc_page_btn")
        self.rpc_page_btn.setGeometry(QRect(-10, 140, 141, 34))
        sizePolicy1.setHeightForWidth(self.rpc_page_btn.sizePolicy().hasHeightForWidth())
        self.rpc_page_btn.setSizePolicy(sizePolicy1)
        self.rpc_page_btn.setStyleSheet(u" \n"
"color: rgb(0, 0, 0);")
        self.rpg_page_btn = QPushButton(self.menu_button_holder)
        self.rpg_page_btn.setObjectName(u"rpg_page_btn")
        self.rpg_page_btn.setGeometry(QRect(-10, 190, 151, 34))
        sizePolicy1.setHeightForWidth(self.rpg_page_btn.sizePolicy().hasHeightForWidth())
        self.rpg_page_btn.setSizePolicy(sizePolicy1)
        self.rpg_page_btn.setStyleSheet(u" \n"
"color: rgb(0, 0, 0);")
        self.rrc_page_btn = QPushButton(self.menu_button_holder)
        self.rrc_page_btn.setObjectName(u"rrc_page_btn")
        self.rrc_page_btn.setGeometry(QRect(-20, 240, 161, 34))
        sizePolicy1.setHeightForWidth(self.rrc_page_btn.sizePolicy().hasHeightForWidth())
        self.rrc_page_btn.setSizePolicy(sizePolicy1)
        self.rrc_page_btn.setStyleSheet(u" \n"
"color: rgb(0, 0, 0);")
        self.results_page_btn = QPushButton(self.menu_button_holder)
        self.results_page_btn.setObjectName(u"results_page_btn")
        self.results_page_btn.setGeometry(QRect(-20, 290, 161, 34))
        sizePolicy1.setHeightForWidth(self.results_page_btn.sizePolicy().hasHeightForWidth())
        self.results_page_btn.setSizePolicy(sizePolicy1)
        self.results_page_btn.setStyleSheet(u" \n"
"color: rgb(0, 0, 0);")
        self.frame_2 = QFrame(self.menu_button_holder)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(6, 6, 108, 70))
        self.frame_2.setMinimumSize(QSize(70, 70))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.pushButton_14 = QPushButton(self.frame_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(10, 20, 91, 34))
        # icon = QIcon()
        # icon.addFile(u"../burger-menu-svgrepo-com (1).svg", QSize(), QIcon.Normal, QIcon.Off)
        # self.pushButton_14.setIcon(icon)

        self.horizontalLayout_2.addWidget(self.menu_button_holder)

        self.stackedWidget = QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setMaximumSize(QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet(u"background-color: rgba(53, 51, 51,0.3)")
        self.info_page = QWidget()
        self.info_page.setObjectName(u"info_page")
        self.label = QLabel(self.info_page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, -10, 191, 40))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        # font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: black")
        self.scrollArea = QScrollArea(self.info_page)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 40, 921, 681))
        font1 = QFont()
        font1.setPointSize(12)
        self.scrollArea.setFont(font1)
        self.scrollArea.setStyleSheet(u"background-color: white;\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 917, 677))
        self.frame = QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 931, 71))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(8, 8, 161, 18))
        self.label_6.setStyleSheet(u"color: black;")
        self.textEdit = QTextEdit(self.frame)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(8, 32, 901, 31))
        self.textEdit.setStyleSheet(u"border: 2px solid black;")
        self.frame_4 = QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(0, 80, 921, 71))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.frame_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(8, 8, 121, 18))
        self.label_7.setStyleSheet(u"color: black;")
        self.textEdit_2 = QTextEdit(self.frame_4)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(8, 32, 901, 31))
        self.textEdit_2.setStyleSheet(u"border: 2px solid black;")
        self.frame_6 = QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(0, 160, 921, 71))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_9 = QLabel(self.frame_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(8, 8, 141, 18))
        self.label_9.setStyleSheet(u"color: black;")
        self.textEdit_4 = QTextEdit(self.frame_6)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(8, 32, 901, 31))
        self.textEdit_4.setStyleSheet(u"border: 2px solid black;")
        self.frame_5 = QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 240, 911, 81))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(8, 8, 181, 18))
        self.label_8.setStyleSheet(u"color: black;")
        # self.kdatecombobox = KDateComboBox(self.frame_5)
        # self.kdatecombobox.setObjectName(u"kdatecombobox")
        # self.kdatecombobox.setGeometry(QRect(10, 30, 151, 32))
        # self.kdatecombobox.setStyleSheet(u"color: black;")
        self.label_10 = QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 330, 271, 21))
        font2 = QFont()
        font2.setUnderline(True)
        self.label_10.setFont(font2)
        self.label_10.setStyleSheet(u"color: black;")
        self.label_11 = QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 380, 121, 21))
        self.label_11.setStyleSheet(u"color: black;")
        self.label_12 = QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(190, 380, 121, 21))
        self.label_12.setStyleSheet(u"color: black;")
        self.label_13 = QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(330, 380, 181, 21))
        self.label_13.setStyleSheet(u"color: black;")
        self.label_14 = QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 410, 271, 21))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setUnderline(True)
        # font3.setWeight(75)
        self.label_14.setFont(font3)
        self.label_14.setStyleSheet(u"color: black;")
        self.label_15 = QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 440, 251, 20))
        self.radioButton = QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(20, 470, 105, 22))
        self.radioButton.setStyleSheet(u"color: black;")
        self.radioButton_2 = QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(170, 470, 105, 22))
        self.radioButton_2.setStyleSheet(u"color: black;")
        self.radioButton_3 = QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(320, 470, 105, 22))
        self.radioButton_3.setStyleSheet(u"color: black")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.info_page)
        self.rpc_page = QWidget()
        self.rpc_page.setObjectName(u"rpc_page")
        self.label_2 = QLabel(self.rpc_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, -10, 191, 40))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: black;")
        self.stackedWidget.addWidget(self.rpc_page)
        self.rpg_page = QWidget()
        self.rpg_page.setObjectName(u"rpg_page")
        self.label_3 = QLabel(self.rpg_page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, -10, 191, 40))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: black;")
        self.stackedWidget.addWidget(self.rpg_page)
        self.rrc_page = QWidget()
        self.rrc_page.setObjectName(u"rrc_page")
        self.label_4 = QLabel(self.rrc_page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, -10, 191, 40))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: black;")
        self.stackedWidget.addWidget(self.rrc_page)
        self.results_page = QWidget()
        self.results_page.setObjectName(u"results_page")
        self.label_5 = QLabel(self.results_page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, -10, 121, 40))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: black")
        self.stackedWidget.addWidget(self.results_page)

        self.horizontalLayout_2.addWidget(self.stackedWidget)


        self.horizontalLayout.addWidget(self.frame_3)


        self.verticalLayout.addWidget(self.Content_Area)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.informations_page_btn.setText(QCoreApplication.translate("MainWindow", u"Informations", None))
        self.rpc_page_btn.setText(QCoreApplication.translate("MainWindow", u"RPC", None))
        self.rpg_page_btn.setText(QCoreApplication.translate("MainWindow", u"RPG", None))
        self.rrc_page_btn.setText(QCoreApplication.translate("MainWindow", u"RRC", None))
        self.results_page_btn.setText(QCoreApplication.translate("MainWindow", u"Resultats", None))
        self.pushButton_14.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Informations", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Nom de l'operateur", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Nom du projet", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Identification du residu", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Date de melange", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Contenant pour le moulage", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Section et hauteur", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Rayon et hauteur", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Longeur, largeur et hauteur", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Composante liant hydralique", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Nombre de ciments pour le liant", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"RPC", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"RPG", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"RRC", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Resultats", None))
    # retranslateUi

